"""Application layer ports: interfaces the services need, implemented by adapters in monishield/infrastructure/.

Services receive `ctx` (on the server: `app.state`, assembled in monishield/interfaces/api/app.py) containing:
  cfg            running configuration (monishield.domain.config_model.Config)
  auth           AccountStore       accounts, audit, import jobs, notification log   infrastructure/auth.py (Auth)
  warehouse      Warehouse          ingest + folder data in DuckDB                  infrastructure/warehouse.py (DuckWarehouse)
  logfolders     LogFolders         log folders on disk (main folder + inbox)       infrastructure/logfolders.py
  s3             S3Gateway          S3 download, folder listing, connection test    infrastructure/importer.py (S3Gateway)
  env            EnvStore           .env file + environment variables               infrastructure/envfile.py (EnvStore)
  channels       NotificationChannels Telegram / Discord / email                   infrastructure/notify_channels.py (Channels)
  mailer         Mailer             letters through the mail server (SMTP)          infrastructure/mailer.py (Mailer)
  kafka_client   KafkaClient        consumer + Kafka message check                  infrastructure/kafka_client.py (KafkaClient)
  inbox          Inbox (factory)    buffer of Kafka lines -> inbox files            infrastructure/inbox.py (Spool)
  uploads        UploadStore        temporary upload files                          infrastructure/uploads.py (Uploads)
  maxmind        MaxMindProbe       MaxMind key test                                infrastructure/refdata.py (probe_maxmind)
  ingest, imports, alerts, kafka, retention, resets    other application services (calling each other through ctx)

User-facing errors are raised as monishield.domain.errors.Fail (code + message + status); the interface layer
translates them to HTTP. The Protocols below are only documentation + type checking; nothing inherits from them.
"""
from typing import Any, Callable, ContextManager, Iterable, Mapping, Protocol


class AccountStore(Protocol):
    def audit(self, action: str, user: Any = None, detail: str | None = None, ip: str | None = None) -> None: ...
    def job_create(self, by: str, bucket: str, prefix: str, folder: str, status: str = 'running') -> int: ...
    def job_finish(self, job_id: int, status: str, bytes: int | None = None, files: int | None = None, skipped: int | None = None,
                   message: str | None = None) -> None: ...
    def job_get(self, job_id: int) -> dict | None: ...
    def job_list(self, limit: int) -> list: ...
    def alert_seen(self, key: str) -> bool: ...
    def alert_add(self, key: str, event: str, channel: str, ok: bool, summary: str | None = None, error: str | None = None) -> None: ...
    def alert_list(self, limit: int) -> list: ...
    def setting_get(self, key: str) -> dict | None: ...
    def setting_delete(self, key: str) -> None: ...


class Warehouse(Protocol):
    def ingest(self, folder: str | None = None, force: bool = False, progress: Callable | None = None) -> dict: ...
    def snapshot_wanted(self, missing_only: bool = False) -> bool: ...
    def snapshot(self) -> None: ...
    def exclusive(self) -> ContextManager: ...
    def derive_all(self, folder: str | None = None) -> list: ...
    def forget(self, folder: str) -> int: ...
    def last_run(self) -> dict | None: ...
    def known_folders(self) -> set: ...
    def ignored(self) -> set: ...
    def newest_folder(self) -> str | None: ...
    def folder_table(self) -> tuple[dict, dict]: ...
    def ignore(self, folder: str, by: str) -> None: ...
    def unignore(self, folder: str) -> bool: ...
    def folder_facts(self, folder: str, crs: bool) -> dict: ...
    def ip_locations(self) -> Mapping[str, tuple]: ...
    def services(self) -> list: ...


class LogFolders(Protocol):
    def dates(self) -> tuple[set, set]: ...
    def on_disk(self, folder: str) -> tuple[bool, bool]: ...
    def in_log_dir(self, folder: str) -> bool: ...
    def source(self, folder: str) -> str | None: ...
    def new_folders(self, known: Iterable[str]) -> list: ...
    def from_s3(self, folders: Iterable[str]) -> set: ...
    def inbox_ok(self, folder: str) -> bool: ...
    def remove_inbox(self, folder: str) -> bool: ...


class S3Gateway(Protocol):
    creds: Any
    def library_ok(self) -> bool: ...
    def ready(self) -> None: ...
    def run(self, url: str, dry_run: bool = False, progress: Callable | None = None) -> dict: ...
    def list_folders(self, bucket: str, base: str) -> list: ...
    def probe(self, bucket: str, prefix: str) -> None: ...
    def error(self, e: Exception) -> Exception: ...


class EnvStore(Protocol):
    path: str
    def values(self) -> dict: ...
    def environ(self) -> Mapping[str, str]: ...
    def exists(self) -> bool: ...
    def writable(self) -> bool: ...
    def write(self, changes: dict) -> list: ...


class Mailer(Protocol):
    def ready(self) -> bool: ...
    def send(self, letter: dict, to: str) -> None: ...


class NotificationChannels(Protocol):
    names: tuple
    def send(self, name: str, channel: dict, title: str, text: str) -> None: ...


class KafkaClient(Protocol):
    no_library: str
    def library_ok(self) -> bool: ...
    def consumer(self, cfg: Any) -> Any: ...
    def peek(self, cfg: Any, n: int = 10) -> dict: ...
    def error(self, e: Exception) -> Exception: ...


class Inbox(Protocol):
    n: int
    def add(self, rec: dict) -> str: ...
    def flush(self) -> dict: ...


class UploadStore(Protocol):
    def create(self, by: str, files: list) -> str: ...
    def get(self, uid: str, by: str) -> dict: ...
    def target(self, uid: str, by: str, i: int) -> tuple[dict, str]: ...
    def received(self, uid: str, i: int) -> None: ...
    def finish(self, uid: str, by: str) -> dict: ...
    def drop(self, uid: str) -> None: ...
